apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
spec:
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank
        image: zoomcamp-model:hw10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"            
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9696